hydra:
  run:
    dir: ./cifar/outputs/${now:%Y-%m-%d}-${now:%H-%M-%S}
  sweep:
    dir: ./cifar/outputs/${now:%Y-%m-%d}-${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

defaults:
  - dataset: cifar10
  - model: simple
  - inner_loss: scalar_label_smoothing
  - inner_optimizer: adam
  - inner_lr_scheduler: none
  - outer_optimizer: sgd
  - outer_lr_scheduler: none
  - _self_

#Same dataset for inner and outer
#ResNet
#Loss-difference for outer steps
#2D comparison
#Regularization for inner

#Vector+Matrix smoothing
#Different initializations

batch_size: 64
cuda: true
shuffle_data: true
seed: 0
load_model_file: null
bilevel: true
epochs: 7
outer_batches_per_epoch: 1000
inner_iterations: 5
save_model_file: "ncc_bilevel"
label_noise_transition_matrix: [
        [0.85,    0,    0,    0,    0,    0,    0, 0.15,    0,    0],
        [   0, 0.85,    0, 0.15,    0,    0,    0,    0,    0,    0],
        [   0,    0, 0.85,    0,    0, 0.15,    0,    0,    0,    0],
        [   0,    0,    0, 0.85,    0,    0,    0,    0,    0, 0.15],
        [   0, 0.15,    0,    0, 0.85,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0, 0.85, 0.15,    0,    0,    0],
        [0.15,    0,    0,    0,    0,    0, 0.85,    0,    0,    0],
        [   0,    0,    0,    0, 0.15,    0,    0, 0.85,    0,    0],
        [   0,    0, 0.15,    0,    0,    0,    0,    0, 0.85,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0, 0.15, 0.85]
      ]
train_noise: true
validation_noise: false
test_noise: false