hydra:
  run:
    dir: ./cifar/outputs/${now:%Y-%m-%d}-${now:%H-%M-%S}
  sweep:
    dir: ./cifar/outputs/${now:%Y-%m-%d}-${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

defaults:
  - dataset: cifar10
  - model: simple
  - inner_loss: scalar_label_smoothing
  - inner_optimizer: adam
  - inner_lr_scheduler: none
  - outer_optimizer: sgd
  - outer_lr_scheduler: none
  - _self_

batch_size: 64
cuda: true
shuffle_data: true
seed: 0
load_model_file: null
bilevel: true
epochs: 50
outer_batches_per_epoch: 500
inner_iterations: 5
save_model_file: null
label_noise_transition_matrix: null #[
#        [0.85,    0,    0,    0,    0,    0,    0, 0.15,    0,    0], #Probabilities for class 0 to become class i
#        [   0, 0.85,    0, 0.15,    0,    0,    0,    0,    0,    0], #Probabilities for class 1 to become class i
#        [   0,    0, 0.85,    0,    0, 0.15,    0,    0,    0,    0], #Probabilities for class 2 to become class i
#        [   0,    0,    0, 0.85,    0,    0,    0,    0,    0, 0.15], #Probabilities for class 3 to become class i
#        [   0, 0.15,    0,    0, 0.85,    0,    0,    0,    0,    0], #Probabilities for class 4 to become class i
#        [   0,    0,    0,    0,    0, 0.85, 0.15,    0,    0,    0], #Probabilities for class 5 to become class i
#        [0.15,    0,    0,    0,    0,    0, 0.85,    0,    0,    0], #Probabilities for class 6 to become class i
#        [   0,    0,    0,    0, 0.15,    0,    0, 0.85,    0,    0], #Probabilities for class 7 to become class i
#        [   0,    0, 0.15,    0,    0,    0,    0,    0, 0.85,    0], #Probabilities for class 8 to become class i
#        [   0,    0,    0,    0,    0,    0,    0,    0, 0.15, 0.85]  #Probabilities for class 9 to become class i
#      ]
train_noise: false #true
validation_noise: false
test_noise: false